//logged in user actions
export const LOGGED_IN_USER_CLEAR_ALL_DATA = "LOGGED_IN_USER_CLEAR_ALL_DATA";
export const LOGGED_IN_USER_SET_AUTH_TOKEN = "LOGGED_IN_USER_SET_AUTH_TOKEN";
export const LOGGED_IN_USER_SET_USER = "LOGGED_IN_USER_SET_USER";
export const LOGGED_IN_USER_SET_USER_NAME = "LOGGED_IN_USER_SET_USER_NAME";
export const LOGGED_IN_USER_SET_IS_PIN_SET = "LOGGED_IN_USER_SET_IS_PIN_SET";
export const LOGGED_IN_USER_SET_CODEPUSH_DEPLOYEMENT_STAGING =
  "LOGGED_IN_USER_SET_CODEPUSH_DEPLOYEMENT_STAGING";
export const LOGGED_IN_USER_SET_LATEST_DO_YOU_KNOW_READ_ID =
  "LOGGED_IN_USER_SET_LATEST_DO_YOU_KNOW_READ_ID";

//ui actions
export const UI_INCREMENT_APP_OPEN = "UI_INCREMENT_APP_OPEN";
export const UI_SET_FCM_TOKEN = "UI_SET_FCM_TOKEN";
export const UI_SET_LANGUAGE = "UI_SET_LANGUAGE";
export const UI_SET_SCREEN_TO_OPEN_AFTER_LOGIN =
  "UI_SET_SCREEN_TO_OPEN_AFTER_LOGIN";
export const UI_SET_HAS_BLANK_DASHBOARD_TOUR_SHOWN =
  "UI_SET_HAS_BLANK_DASHBOARD_TOUR_SHOWN";
export const UI_SET_HAS_DASHBOARD_TOUR_SHOWN =
  "UI_SET_HAS_DASHBOARD_TOUR_SHOWN";
export const UI_SET_HAS_EHOME_TOUR_SHOWN = "UI_SET_HAS_EHOME_TOUR_SHOWN";
export const UI_SET_HAS_UPLOAD_BILL_TOUR_SHOWN =
  "UI_SET_HAS_UPLOAD_BILL_TOUR_SHOWN";
export const UI_SET_HAS_PRODUCT_CARD_SHOWN = "UI_SET_HAS_PRODUCT_CARD_SHOWN";
export const UI_SET_HAS_UPLOAD_DOC_TOUR_SHOWN =
  "UI_SET_HAS_UPLOAD_DOC_TOUR_SHOWN";
export const UI_UPDATE_AVAILABLE_SCREEN_TIMESTAMP =
  "UI_UPDATE_AVAILABLE_SCREEN_TIMESTAMP";
export const UI_SET_RATE_US_DIALOG_TIMESTAMP =
  "UI_SET_RATE_US_DIALOG_TIMESTAMP";
