//logged in user actions
export const LOGGED_IN_USER_SET_AUTH_TOKEN = "LOGGED_IN_USER_SET_AUTH_TOKEN";
export const LOGGED_IN_USER_SET_FCM_TOKEN = "LOGGED_IN_USER_SET_FCM_TOKEN";
export const LOGGED_IN_USER_SET_USER = "LOGGED_IN_USER_SET_USER";

//ui actions
export const UI_SET_SCREEN_TO_OPEN_AFTER_LOGIN =
  "UI_SET_SCREEN_TO_OPEN_AFTER_LOGIN";
export const UI_SET_HAS_BLANK_DASHBOARD_TOUR_SHOWN =
  "UI_SET_HAS_BLANK_DASHBOARD_TOUR_SHOWN";
export const UI_SET_HAS_DASHBOARD_TOUR_SHOWN =
  "UI_SET_HAS_DASHBOARD_TOUR_SHOWN";
export const UI_SET_HAS_EHOME_TOUR_SHOWN = "UI_SET_HAS_EHOME_TOUR_SHOWN";
export const UI_SET_HAS_UPLOAD_DOC_TOUR_SHOWN =
  "UI_SET_HAS_UPLOAD_DOC_TOUR_SHOWN";
export const UI_SET_HAS_UPDATE_APP_SCREEN_SHOWN =
  "UI_SET_HAS_UPDATE_APP_SCREEN_SHOWN";
