const EXPENSE_TYPES = {
  AUTOMOBILE: "AUTOMOBILE",
  ELECTRONICS: "ELECTRONICS_ELECTRICALS",
  FURNITURE: "FURNITURE",
  MEDICAL_DOCS: "MEDICAL_DOCS",
  PERSONAL: "PERSONAL",
  VISITING_CARD: "VISITING_CARD",
  TRAVEL: "TRAVEL",
  HEALTHCARE: "HEALTHCARE",
  FASHION: "FASHION",
  SERVICES: "SERVICES",
  HOME: "HOME",
  REPAIR: "REPAIR"
};

const MAIN_CATEGORY_IDS = {
  FURNITURE: 1,
  ELECTRONICS: 2,
  AUTOMOBILE: 3,
  TRAVEL: 4,
  HEALTHCARE: 5,
  SERVICES: 6,
  FASHION: 7,
  HOUSEHOLD: 8,
  OTHERS: 9,
  PERSONAL: 10
};

const SCREENS = {
  ADD_EDIT_WARRANTY_SCREEN: "ADD_EDIT_WARRANTY_SCREEN",
  ADD_EDIT_EXPENSE_SCREEN: "ADD_EDIT_EXPENSE_SCREEN",
  ADD_PRODUCT_SCREEN: "ADD_PRODUCT_SCREEN",
  ADD_PRODUCTS_SCREEN: "ADD_PRODUCTS_SCREEN",
  ASC_SEARCH_SCREEN: "ASC_SEARCH_SCREEN",
  BILLS_POPUP_SCREEN: "BILLS_POPUP_SCREEN",
  DASHBOARD_SCREEN: "DASHBOARD_SCREEN",
  DOCS_UNDER_PROCESSING_SCREEN: "DOCS_UNDER_PROCESSING_SCREEN",
  INSIGHTS_SCREEN: "INSIGHTS_SCREEN",
  INTRO_SCREEN: "INTRO_SCREEN",
  MAILBOX_SCREEN: "MAILBOX_SCREEN",
  MAIN_CATEGORY_SCREEN: "MAIN_CATEGORY_SCREEN",
  MORE_SCREEN: "MORE_SCREEN",
  PRODUCT_DETAILS_SCREEN: "PRODUCT_DETAILS_SCREEN",
  PROFILE_SCREEN: "PROFILE_SCREEN",
  UPLOAD_DOCUMENT_SCREEN: "UPLOAD_DOCUMENT_SCREEN",
  ASC_SCREEN: "ASC_SCREEN",
  EHOME_SCREEN: "EHOME_SCREEN",
  FAQS_SCREEN: "FAQS_SCREEN",
  FORCE_UPDATE_SCREEN: "FORCE_UPDATE_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SEARCH_SCREEN: "SEARCH_SCREEN",
  SNACKBAR_SCREEN: "SNACKBAR_SCREEN",
  TERMS_SCREEN: "TERMS_SCREEN",
  TIPS_SCREEN: "TIPS_SCREEN",
  TOTAL_TAX_SCREEN: "TOTAL_TAX_SCREEN",
  TRANSACTIONS_SCREEN: "TRANSACTIONS_SCREEN",
  VERIFY_SCREEN: "VERIFY_SCREEN"
};

export { MAIN_CATEGORY_IDS, SCREENS, EXPENSE_TYPES };
