const MAIN_CATEGORY_IDS = {
  FURNITURE: 1,
  ELECTRONICS: 2,
  AUTOMOBILE: 3,
  TRAVEL: 4,
  HEALTHCARE: 5,
  SERVICES: 6,
  FASHION: 7,
  HOUSEHOLD: 8,
  OTHERS: 9,
  PERSONAL: 10
};

export { MAIN_CATEGORY_IDS };
