# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BinBill' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BinBill
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  # pod 'RNShare', :path => '../node_modules/react-native-share'

  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  pod 'FirebaseMessaging'
  pod 'Firebase/Core'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  target 'BinBillTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BinBill-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BinBill-tvOS

  target 'BinBill-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
