# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BinBill_RN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BinBill_RN
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'BinBill_RNTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
  end

end

target 'BinBill_RN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BinBill_RN-tvOS

  target 'BinBill_RN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
